name: 'Deploy to Development Environment'

on:
  workflow_call:
  workflow_dispatch:

env:
  TF_VERSION: '1.14.6'
  ENVIRONMENT: 'dev'
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


jobs:
  deploy-infra:
    name: 'Deploy to Development Environment'
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        working-directory: infra

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v4
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - run: terraform init

    - id: plan
      run: terraform plan