name: Build and Push Images to Registry

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'backend/**'
  #     - 'store-service/**'
  #     - 'chat-websocket-service/**'
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}

jobs:
  build-push-api:
    name: API Service
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/myguy-api:latest

  build-push-store-service:
    needs: build-push-api
    name: Store Service
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./store-service
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/myguy-store-service:latest

  build-push-chat-service:
    needs: build-push-store-service
    name: Chat Websocket Service
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./chat-websocket-service
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/myguy-chat-websocket-service:latest