name: 'Deploy infra to Development Environment'

on:
  # schedule:
  #   - cron: '0 19 * * *'  # 9pm Amsterdam (CEST, UTC+2)
  workflow_call:
    inputs:
      action:
        type: string
        description: 'Terraform action to perform (plan or apply)'
        required: true
        default: 'plan'
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Terraform action to perform'
        required: true
        options:
          - plan
          - apply

env:
  TF_VERSION: '1.14.6'
  ENVIRONMENT: 'dev'
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


jobs:
  deploy-infra:
    name: 'Deploy to Development Environment'
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        working-directory: infra

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v4
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - run: terraform init

    - id: plan
      run: terraform plan

    - id: apply
      run: terraform ${{ github.event_name == 'schedule' && 'destroy' || inputs.action }} -auto-approve